### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by Wes-V3** [robpearc/DeepFoldRNA#3]
When "Predicting Restraints for Network 1 Parameter File weight_3", I got the error:
```
Traceback (most recent call last):
  File "runDeepFoldRNA.py", line 452, in <module>
    run_prediction(args.input_dir,args.generate_all_models)
  File "runDeepFoldRNA.py", line 196, in run_prediction
    output = model(feature_dict)
  File "/home/RNA_structure_prediction/Algorithms/DeepFoldRNA-main/conda_local/conda/envs/deepfoldrna/li
    return forward_call(*input, **kwargs)
  File "/home/RNA_structure_prediction/Algorithms/DeepFoldRNA-main/network/network_1.py", line 71, in fo
    msa_recycle, pair_recycle, seq_recycle = self.iteration(features, msa_recycle, pair_recycle, seq_recycle,
  File "/home/RNA_structure_prediction/Algorithms/DeepFoldRNA-main/network/network_1.py", line 47, in it
    pair_embed_ss = self.pair_transformer_layers(pair_embed_ss)
  File "/home/RNA_structure_prediction/Algorithms/DeepFoldRNA-main/conda_local/conda/envs/deepfoldrna/li
    return forward_call(*input, **kwargs)
  File "/home/RNA_structure_prediction/Algorithms/DeepFoldRNA-main/network/pair_transformer.py", line 40
    pair_embed = self.pair_transformer_blocks[i](pair_embed)
  File "/home/RNA_structure_prediction/Algorithms/DeepFoldRNA-main/conda_local/conda/envs/deepfoldrna/li
    return forward_call(*input, **kwargs)
  File "/home/RNA_structure_prediction/Algorithms/DeepFoldRNA-main/network/pair_transformer.py", line 24
    pair_embed = pair_embed + self.drop_pair_row(self.triangle_att_start(pair_embed))
  File "/home/RNA_structure_prediction/Algorithms/DeepFoldRNA-main/conda_local/conda/envs/deepfoldrna/li
    return forward_call(*input, **kwargs)
  File "/home/RNA_structure_prediction/Algorithms/DeepFoldRNA-main/network/pair.py", line 45, in forward
    attn_map = torch.einsum("ijhd,ikhd->hijk", query, key) + pair_bias
RuntimeError: CUDA out of memory. Tried to allocate 11.12 GiB (GPU 0; 23.70 GiB total capacity; 14.23 GiB already allocated; 7.49 GiB free; 14.24 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

While in fact, when I run `nvidia-smi`, I got
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.56       Driver Version: 460.56       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    On   | 00000000:01:00.0 Off |                  N/A |
| 37%   46C    P8    25W / 350W |      3MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 3090    On   | 00000000:24:00.0 Off |                  N/A |
| 74%   57C    P8    31W / 350W |      3MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by robpearc** [comment]
Depending on how large your sequence and MSA are, the program may use more memory than is available on your GPU, upwards of 30 GB. You can try running it on a device with more memory capacity or on a CPU.
